### PR TITLE
Upgraded gems and fixed warnings.

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded ruby to 2.4.2.
 * Upgraded Rails to 4.2.10.
 * Rebuilt Gemfile.lock file to upgrade other gems.
 * Fixed several "rake" warnings.

### CODE REVIEW

**Comment by jasnow** [comment]
I will try TravisCI again tomorrow morning.

**Comment by orendon** [comment]
@jasnow 👍

**Comment by jasnow** [comment]
Appears I can not restart TravisCI  owned by you. Please log into TravisCI and push the RESTART button. Thanks.

**Comment by jasnow** [comment]
@orendon -- Ready

**Comment by jasnow** [comment]
TravisCI is green now -- Good

**Comment by jasnow** [comment]
I can get a green TravisCI run so I'm closing this PR.

**Pull request closed without merging**
